### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'parser-model/vocab'

### ISSUE THREAD

**Issue by WUT-Post** [zhangmeishan/DepSAWR#1]
i cant resolve this where is vocab in the code
File "driver/Train.py", line 170, in <module>
    dep_vocab = pickle.load(open(parser_config.load_vocab_path, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'parser-model/vocab'
dep_vocab = pickle.load(open(parser_config.load_vocab_path, 'rb'))
    dep_vec = dep_vocab.create_pretrained_embs(parser_config.pretrained_embeddings_file)

    parser_model = ParserModel(dep_vocab, parser_config, dep_vec)
    parser_model.load_state_dict(torch.load(parser_config.load_model_path, \
                                map_location=lambda storage, loc: storage))

**Comment by zhangmeishan** [comment]
I guess you need to train the dependency parser with my dependency parser first: https://github.com/zhangmeishan/BiaffineDParser

**Comment by WUT-Post** [comment]
Can you share with me your CTB 5 dataset , I want to reimplement your experiment

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by conquerSelf** [comment]
Dear Teacher Zhang! I am very interested to see your article integrating grammatical information into NMT! However, I still lacked the CTB5.1 data during the reproduction process. Can you share this data set? Thanks a lot if you can! My email 2244305723@qq.com
